Remove upper margin in log container (#34)
taskcluster/unified-logviewer pull request #35
Opened 2017-04-01 16:50 UTC by tojon

This removes the upper margin in the log container, to remove the unnecessary real estate consumed when viewing the topmost log lines.

Currrent:

![current](https://cloud.githubusercontent.com/assets/3660661/24580611/c2bf6c34-16d8-11e7-948c-1dea323969e7.jpg)

Proposed:

![proposed](https://cloud.githubusercontent.com/assets/3660661/24580614/d2ee2a14-16d8-11e7-85c9-0484efcd06a7.jpg)

Treeherder current:

![treeherdercurrent](https://cloud.githubusercontent.com/assets/3660661/24580646/78da31f2-16d9-11e7-92bf-2f4fb1e0e627.jpg)

Treeherder proposed:

![treeherderproposed](https://cloud.githubusercontent.com/assets/3660661/24580653/8ab3f4bc-16d9-11e7-9dae-913f6f7686bd.jpg)

Other than simulating it above in TaskCluster and Treeherder in inspector, I can't vouch for any local testing of this change due to unified-logviewer install issues in Issue https://github.com/taskcluster/unified-logviewer/issues/33

2017-04-01 18:46 UTC, eliperelman commented
LGTM, although you'll also need to modify this hardcoded value as well:

https://github.com/taskcluster/unified-logviewer/blob/b45e1ea88dba1acb74d9fdab647368564139c12a/src/LogViewer/index.js#L281

2017-04-06 18:46 UTC, tojon commented
Cool. I'll include that and squash. I have the unified-logviewer running locally now, loading logs. However I notice what I understand to be `jumpToLine` behavior while visible in TaskCluster, is not present in my local server? Clicking on a line number locally, doesn't pop the line to the top of the view, as I would expect it would? Anyway, I'll include the change.

2017-04-16 21:01 UTC, tojon commented
@eliperelman just checking on this PR in case it fell through the cracks.

2017-04-20 15:49 UTC, eliperelman requested changes
I missed another reference to 35. You may want to search to see if there are any others.

2017-04-20 15:49 UTC, eliperelman commented on src/app.css
>    height: calc(100% - 35px);
This line here as well.

2017-05-01 17:00 UTC, tojon commented
> I missed another reference to 35. You may want to search to see if there are any others.

Ya, I'll remove that also. I don't see any others in the repo.

2017-05-01 17:36 UTC, tojon commented on src/app.css
> -  position: relative;
This didn't appear required either.

2017-05-04 00:43 UTC, eliperelman approved these changes

2017-05-04 00:43 UTC, merged

2017-05-04 00:43 UTC, eliperelman commented
Thanks!