add readme to repo
taskcluster/unified-logviewer pull request #4
Opened 2016-09-26 00:28 UTC by helfi92

2016-09-26 00:29 UTC, helfi92 commented
@eliperelman

2016-10-10 14:26 UTC, eliperelman requested changes

2016-10-10 14:26 UTC, eliperelman commented on README.md
> +$ git clone https://github.com/taskcluster/unified-logviewer.git
This should probably be fork and clone rather than clone from this repo.

2016-10-10 14:26 UTC, eliperelman commented on README.md
> +localhost:4000/?url=https://public-artifacts.taskcluster.net/5qB6Zqc0Tw2_wkKwHgGNGQ/0/public/logs/live_backing.log
Add `http://` to the beginning of this URL.

2016-10-10 23:34 UTC, helfi92 commented
Added your proposed changes :)

2016-10-12 14:53 UTC, eliperelman approved these changes

2016-10-12 14:53 UTC, merged