Jump to line feature
taskcluster/unified-logviewer pull request #5
Opened 2016-10-01 15:09 UTC by helfi92

To experiment with this feature, select a line number in the log and then refresh the page. the log will take you to the selected line.

2016-10-10 14:41 UTC, eliperelman requested changes

2016-10-10 14:41 UTC, eliperelman commented on src/LogViewer/index.js
> +      LINE_CHUNK: 0,
This property should not be uppercased.

2016-10-10 14:41 UTC, eliperelman commented on src/LogViewer/index.js
> +    const { highlightStart } = this.state;
`highlightStart` and the jump line should not be related for this log viewer. I know GitHub works differently, but we should introduce a new property for a `jumpToLine` in `LogViewer` so we can move to lines separately from highlighting them.

2016-10-10 14:41 UTC, eliperelman commented on src/LogViewer/chunk-worker.js
> +  self.postMessage(JSON.stringify({ type: 'update', chunkHeights, offset, LINE_CHUNK }));
`LINE_CHUNK` is a constant to this file, but being something passed to `LogViewer` makes it not constant to the other file, so it should not be uppercased here. Something like:

```js
{  lineChunk: LINE_CHUNK  }
```

2016-10-10 14:41 UTC, eliperelman commented on src/LazyList/index.js
> -      renderIndices: Range(0, 0)
The functionality seems OK, but having the it located in `LazyList` would violate this component's concerns. `LazyList` should only care about the loading and unloading of list items based on scroll position. It does not have knowledge of lines, or the contents of its lists, or how to jump to a certain line. This functionality should probably be in the `LogViewer` component, by using the line knowledge to change the scroll position, which would then cause `LazyList` to update its loaded containers, which should already be handled.

2016-10-11 01:44 UTC, helfi92 commented
@eliperelman, I totally agree with you. Keeping the components functional is the way to go. I can implement a jumpToLine function in LogViewer that can take a lineNumber and scroll the window by an x amount of pixels and then let LazyList take control. I am aware there is currently no UI that can take a lineNumber. Do we need one or is that not important for now.
I can also implement a jumpToHighlight function which will run if and only if there is a highlightStart number in the URL. I think that's a great feature to have. Thoughts?

2016-10-11 22:45 UTC, helfi92 commented
@eliperelman latest commit addresses your comments. Looks a lot cleaner :)

2016-10-12 14:59 UTC, eliperelman requested changes

2016-10-12 14:59 UTC, eliperelman commented on src/LogViewer/chunk-worker.js
> +    type: 'update', chunkHeights, offset,
If you multi-line object properties, put each one on their own line, e.g.:

```js
self.postMessage(JSON.stringify({
  chunkHeights,
  offset,
  type: 'update',
  lineChunk: LINE_CHUNK,
  minLineHeight: MIN_LINE_HEIGHT
}));
```

2016-10-12 14:59 UTC, eliperelman commented on src/LogViewer/index.js
> +    const { highlightStart } = this.state;
I still think this `highlightStart` stuff needs to be removed.

2016-10-12 14:59 UTC, eliperelman commented on src/LogViewer/index.js
> +      <LazyList
This can stay on 1 line.

2016-10-12 14:59 UTC, eliperelman commented on src/LogViewer/index.js
> +    const { minLineHeight, offset } = this.state;
I don't see this method being called outside of `jumpToHighlight`. I think we need to fetch the `lineNumber` for jumping from a new query string/state entry, and then handle jumping once it's loaded, similar to how it's being done in `jumpToHighlight`.

2016-10-12 15:40 UTC, helfi92 commented
Ok, this should do what you suggested. Requesting a review.

2016-10-13 21:13 UTC, eliperelman reviewed
Code looks good, but the line jumping didn't work precisely for me. I tried the following URL:

http://localhost:4000/?url=https%3A%2F%2Fpublic-artifacts.taskcluster.net%2F5qB6Zqc0Tw2_wkKwHgGNGQ%2F0%2Fpublic%2Flogs%2Flive_backing.log&lineNumber=3000

and it put me around line 2550.

2016-10-13 22:47 UTC, helfi92 commented
@eliperelman weird, but for this specific log, the line after 1446 turns into 1001. 

<img width="683" alt="screen shot 2016-10-13 at 6 44 00 pm" src="https://cloud.githubusercontent.com/assets/3766511/19369713/0a692d20-9175-11e6-83e8-38b2dc5ce4ea.png">

Works on the huge log though:
http://localhost:4000/?url=https%3A%2F%2Fqueue.taskcluster.net%2Fv1%2Ftask%2FB8yyH1HORxKkQ9p1Sh0CFA%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive_backing.log&highlightStart=&highlightEnd=&lineNumber=300000

Thoughts?

2016-10-17 13:57 UTC, eliperelman commented
@helfi92 I'm not sure. You may want to try adding some `console.log`s to the code to see if you can debug what the expected coordinates, percentages, and window calculations are.

2016-10-17 15:33 UTC, eliperelman commented
Looks like the line differences are because of some HTML non-escaping in the log. Will fix that in a follow up.

2016-10-17 15:33 UTC, merged